#!/bin/bash
### ALIASES ###
# alias c="/bin/clear; echo; echo; seq 1 (tput cols) | sort -R | spark | lolcat; echo; echo"
# \x1b[2J   <- clears tty
# \x1b[1;1H <- goes to (1, 1) (start)
# alias c="echo -en "\x1b[2J\x1b[1;1H" ; echo; echo; seq 1 (tput cols) | sort -R | spark | lolcat; echo; echo"
# alias config="/usr/bin/git --git-dir=$HOME/.config/dotfiles/ --work-tree=$HOME"
# alias sail="[ -f sail ] && sh sail || sh ./vendor/bin/sail"
alias home_git='/usr/bin/git --work-tree=$HOME --git-dir=$HOME/.home'
# ncdu alias, for checking size on harddrive
# alias disk="ncdu ."
alias ds="dua i"
# alias kubectl="minikube kubectl --"
# mounting my windows partition
# alias winmount="udisksctl mount -b /dev/sda1"
# alias winumount="udisksctl unmount -b /dev/sda1"

# display image with kitty terminal
# alias icat="kitty +kitten icat"

# root privileges
alias doas="sudo --"

if which 'zoxide' &> /dev/null; then # Changing "ls" to "eza"
    alias cd="z"
    alias ..="z .."
    alias ...="z ../.."
    alias .3="z ../../.."
    alias .4="z ../../../.."
    alias .5="z ../../../../.."
else
    alias ..="cd .."
    alias ...="cd ../.."
    alias .3="cd ../../.."
    alias .4="cd ../../../.."
    alias .5="cd ../../../../.."
fi

# nvim and emacs
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias suvim="sudo nvim"
alias vgit="nvim +Neogit"

if which 'eza' &> /dev/null; then # Changing "ls" to "eza"
    alias ls="eza -a --color=always --group-directories-first --icons"
    alias la="eza -al --color=always --group-directories-first --icons"
    alias ll="eza -l --color=always --group-directories-first --icons"
    alias lt="eza -aT --color=always --group-directories-first --icons"
    alias l="eza -aD --color=always --group-directories-first --icons"
    alias l.="eza -a | egrep "^\.""
else
    alias la="ls -al --color=auto"
    alias ll="ls -l --color=auto"
    alias lt="ls -aT --color=auto"
    alias l="ls -aD --color=auto"
    alias l.="ls -a | egrep "^\.""
fi

# pacman and yay
## Pacman alias examples
if which 'pacman' &> /dev/null; then
    alias pacupg="sudo pacman -Syu"         # Synchronize with repositories and then upgrade packages that are out of date on the local system.
    alias pacin="sudo pacman -S"            # Install specific package(s) from the repositories
    alias pacins="sudo pacman -U"           # Install specific package not from the repositories but from a file
    alias pacre="sudo pacman -R"            # Remove the specified package(s), retaining its configuration(s) and required dependencies
    alias pacrem="sudo pacman -Rns"          # Remove the specified package(s), its configuration(s) and unneeded dependencies
    alias pacrep="pacman -Si"               # Display information about a given package in the repositories
    alias pacreps="pacman -Ss"              # Search for package(s) in the repositories
    alias pacloc="pacman -Qi"               # Display information about a given package in the local database
    alias paclocs="pacman -Qs"              # Search for package(s) in the local database
    alias paclo="pacman -Qdt"               # List all packages which are orphaned
    alias pacc="sudo pacman -Scc"           # Clean cache - delete all not currently installed package files
    alias paclf="pacman -Ql"                # List all files installed by a given package
    alias pacexpl="pacman -D --asexp"       # Mark one or more installed packages as explicitly installed
    alias pacimpl="pacman -D --asdep"       # Mark one or more installed packages as non explicitly installed
    alias parsua="paru -Sua --noconfirm"
    alias parsyu="paru -Syu --noconfirm"
    alias unlock="sudo rm /var/lib/pacman/db.lck"
    alias cleanup="sudo pacman -Rns `pacman -Qtdq`"
# get fastest mirrors
    alias mirror="sudo reflector -f 30 -l 30 --number 20 --verbose --save /etc/pacman.d/mirrorlist"
    alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
    alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
    alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
fi

# Colorize grep output (good for log files)
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# confirm before overwriting something
alias cp="cp -i -v"
alias mv="mv -i -v"
alias rm='trash -i -v'

# adding flags
alias df="df -h"
alias free="free -m -h -t"
# alias lynx="lynx -cfg=~/.lynx/lynx.cfg -lss=~/.lynx/lynx.lss -vikeys"
# alias fm="~/.config/vifm/scripts/vifmrun"
# alias vifmg="~/.config/vifm/scripts/vifmimg"
# alias ncmpcpp="ncmpcpp ncmpcpp_directory=$HOME/.config/ncmpcpp/"
# ps
alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
alias psmem="ps auxf | sort -nr -k 4"
alias pscpu="ps auxf | sort -nr -k 3"

# Merge Xresources
alias merge="xrdb -merge ~/.Xresources"

# git
if which 'git' &> /dev/null; then
    alias addup="git add -u"
    alias addall="git add ."
    alias branch="git branch"
    alias checkout="git checkout"
    alias clone="git clone"
    alias commit="git commit -m"
    alias fetch="git fetch"
    alias pull="git pull origin"
    alias push="git push origin"
    alias tag="git tag"
    alias newtag="git tag -a"
fi

# get error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# youtube-dl
if which 'yt-dlp' &> /dev/null; then
    alias yta-aac="yt-dlp --extract-audio --audio-format aac "
    alias yta-best="yt-dlp --extract-audio --audio-format best "
    alias yta-flac="yt-dlp --extract-audio --audio-format flac "
    alias yta-m4a="yt-dlp --extract-audio --audio-format m4a "
    alias yta-mp3="yt-dlp --extract-audio --audio-format mp3 "
    alias yta-opus="yt-dlp --extract-audio --audio-format opus "
    alias yta-vorbis="yt-dlp --extract-audio --audio-format vorbis "
    alias yta-wav="yt-dlp --extract-audio --audio-format wav "
    alias ytv-best="yt-dlp -f bestvideo+bestaudio "
fi

# switch between shells
# I do not recommend switching default SHELL from bash.
alias tonushell="sudo chsh $USER -s /bin/bash && echo \"Now log out.\""
alias tobash="sudo chsh $USER -s /bin/bash && echo \"Now log out.\""
alias tozsh="sudo chsh $USER -s /bin/zsh && echo \"Now log out.\""
alias tofish="sudo chsh $USER -s /bin/fish && echo \"Now log out.\""

# Unlock LBRY tips
alias f="fzf --preview \"bat --color=always --style=numbers --line-range=:500 {}\""
alias ipp="ip -s -c -h a"

alias cat='bat'

alias open="xdg-open"
# cargo
if which 'cargo' &> /dev/null; then
    alias cgc="cargo check"
    alias cgb="cargo build"
    alias cgw="cargo watch"
    alias cge="cargo expand"
    alias cgt="cargo test"
fi

alias tt="gio trash"
alias uflatpak="flatpak --user"
alias neogit='nvim +Neogit'
# alias stmake="/opt/st/stm32cubeide_1.11.2/headless-build.sh"
# alias get_idf=". $HOME/Programming/esp-idf/export.fish"
