#!//bin/bash

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM='xterm-256color';
fi;

export COLORTERM=truecolor
export BASH_CONFIG_DIR="$HOME/.config/bash"
export HISTSIZE='512000';
export HISTFILESIZE="${HISTSIZE}";
export HISTFILE="$BASH_CONFIG_DIR/history"
export HISTCONTROL=ignoredups:erasedups

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";
# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# export QT_STYLE_OVERRIDE="gtk2"
export GTK_USE_PORTAL=1
export GIT_EDITOR="$EDITOR"

export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_VIDEOS_DIR="$HOME/Videos"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="$XDG_DATA_HOME/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share"

# add2path_front "$HOME/bin"
add2path_front "$HOME/.local/bin"
add2path_front "$HOME/.local/share/flatpak/exports/bin"
add2path_front "/var/lib/flatpak/exports/bin"
# add2path_front "$HOME/.platformio/penv/bin"

export_if_exists CC "/usr/bin/clang"
export_if_exists CXX "/usr/bin/clang++"

export_if_exists OPENER       "/usr/bin/xdg-open"
export_if_exists READER       "/usr/bin/zathura"
export_if_exists VIDEO        "/usr/bin/mpv"
export_if_exists IMAGE        "/usr/bin/feh"
export_if_exists BROWSER      "/usr/bin/brave"
export_if_exists TERMINAL     "/usr/bin/alacritty"
export_if_exists FILEMANAGER  "/usr/bin/thunar"
export_if_exists EDITOR       "/usr/bin/nvim"
export_if_exists VISUAL       "/usr/bin/neovide"
export_if_exists POWERMENU    "$HOME/.local/bin/powermenu.sh"
export_if_exists COOMER       "$HOME/.local/bin/coomer"

export_if_exists WINEPREFIX   "$HOME/Wine"
export_if_exists WINE_PREFIX  "$WINEPREFIX"

activate_env "$HOME/.cargo/env"
activate_env "$HOME/export-esp.sh"

export_if_exists JAVA_HOME /opt/android-studio/jbr
export_if_exists ANDROID_HOME "$HOME/Android/Sdk"
[[ -d "$ANDROID_HOME/ndk" ]] && export_if_exists NDK_HOME "$ANDROID_HOME/ndk/$(ls -1 "$ANDROID_HOME/ndk")"

