#!/usr/bin/bash

# Determine size of a file or total size of a directory
function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* ./*;
	fi;
}

# Use Git’s colored diff when available
function diff() {
    git diff --no-index --color-words "$@";
}

# Create a data URL from a file
function dataurl() {
	local mimeType=$(file -b --mime-type "$1");
	if [[ $mimeType == text/* ]]; then
		mimeType="${mimeType};charset=utf-8";
	fi
	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

### ARCHIVE EXTRACTION
# usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

function export_if_exists() {
    [[ -e "$2" ]] && export $1="$2"
}

function add2path_front() {
    local path_to_add="${1:?Need at least 1 arguments}"
    [[ -d "$path_to_add" ]] && export PATH="$path_to_add:$PATH";
}
function activate_env() {
    local path_to_env="${1:?Need at least 1 arguments}"
    [[ -f "$path_to_env" ]] && source $path_to_env;
}

# # navigation
# up () {
#   local d=""
#   local limit="$1"
#
#   # Default to limit of 1
#   if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
#     limit=1
#   fi
#
#   for ((i=1;i<=limit;i++)); do
#     d="../$d"
#   done
#
#   # perform cd. Show error if cd fails
#   if ! cd "$d"; then
#     echo "Couldn't go up $limit dirs.";
#   fi
# }
