#!/usr/bin/bash

export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_VIDEOS_DIR="$HOME/Videos"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="$XDG_DATA_HOME/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share"

function add2path_front() {
    local path_to_add="${1:?Need at least 1 arguments}"
    [[ -d "$path_to_add" ]] && export PATH="$path_to_add:$PATH";
}
function activate_env() {
    local path_to_env="${1:?Need at least 1 arguments}"
    [[ -f "$path_to_env" ]] && source $path_to_env;
}

# add2path_front "$HOME/bin"
add2path_front "$HOME/.local/bin"
add2path_front "$HOME/.local/share/flatpak/exports/bin"
add2path_front "/var/lib/flatpak/exports/bin"
# add2path_front "$HOME/.platformio/penv/bin"

activate_env "$HOME/.cargo/env"
activate_env "$HOME/export-esp.sh"
