#!/usr/bin/bash
#      ___                        ___           ___           ___
#     /  /\           ___        /__/\         /  /\         /  /\
#    /  /::\         /__/\       \  \:\       /  /::\       /  /:/
#   /  /:/\:\        \__\:\       \  \:\     /  /:/\:\     /  /:/
#  /  /::\ \:\       /  /::\       \  \:\   /  /::\ \:\   /  /:/
# /__/:/\:\_\:\   __/  /:/\/  ______\__\:\ /__/:/\:\_\:\ /__/:/
# \__\/~|::\/:/  /__/\/:/~~  \  \::::::::/ \__\/  \:\/:/ \  \:\
#    |  |:|::/   \  \::/      \  \:\~~~~~       \__\::/   \  \:\
#    |  |:|\/     \  \:\       \  \:\           /  /:/     \  \:\
#    |__|:|~       \__\/        \  \:\         /__/:/       \  \:\
#     \__\|                      \__\/         \__\/         \__\/
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# [[ -f "$HOME/.config/bash/prompt" ]]      && source "$HOME/.config/bash/prompt";
[[ -f "$HOME/.config/bash/profile" ]]     && source "$HOME/.config/bash/profile"

### SHOPT
shopt -s autocd         # change to named directory
shopt -s cdspell        # autocorrects cd misspellings
shopt -s cmdhist        # save multi-line commands in history as single line
shopt -s dotglob
shopt -s globstar
shopt -s histappend     # do not overwrite history
shopt -s expand_aliases # expand aliases
shopt -s checkwinsize   # checks term size when bash regains control
shopt -s nocaseglob     # Case-insensitive globbing (used in pathname expansion)
#ignore upper and lowercase when TAB completion
bind -s 'set completion-ignore-case on'
